### ISSUE TITLE
Squad's markers not showing by default

### ISSUE THREAD

**Issue by norekdcs2020** [ArmaForces/FriendlyTracker#26]
Daj optional opt-out, czyli default on :lenny:

**Comment by veteran29** [comment]
Sorry, we're using English on this issue tracker.

**Comment by norekdcs2020** [comment]
Day optional opt-out, chilli default on :lenny:

**Comment by norekdcs2020** [comment]
Please try using optional opt-out instead.

**Comment by norekdcs2020** [comment]
This is an amazing group!
